services:
  ogok-server:
    build: ..
    ports:
      - ${SERVER_PORT}:8080
    depends_on:
      ogok-db:
        condition: service_healthy
  ogok-db:
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_DATABASE}
    volumes:
      - ${DB_VOLUMES}
    ports:
      - ${DB_PORT}:3306
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping" ]
      interval: 5s
      retries: 10