services:
  ogok-server:
    build: ..
    env_file:
      - .env
    environment:
      - SPRING_MAIL_HOST=${SPRING_MAIL_HOST}
      - SPRING_MAIL_PORT=${SPRING_MAIL_PORT}
      - SPRING_MAIL_USERNAME=${SPRING_MAIL_USERNAME}
      - SPRING_MAIL_PASSWORD=${SPRING_MAIL_PASSWORD}
      - SPRING_MAIL_SMTP_SSL_TRUST=${SPRING_MAIL_SMTP_SSL_TRUST}
      - SPRING_MAIL_SMTP_SSL_PROTOCOLS=${SPRING_MAIL_SMTP_SSL_PROTOCOLS}
      - SPRING_MAIL_SMTP_CONNECTIONTIMEOUT=${SPRING_MAIL_SMTP_CONNECTIONTIMEOUT}
      - SPRING_MAIL_SMTP_TIMEOUT=${SPRING_MAIL_SMTP_TIMEOUT}
      - SPRING_MAIL_SMTP_WRITETIMEOUT=${SPRING_MAIL_SMTP_WRITETIMEOUT}
    ports:
      - ${SERVER_PORT}:8080
    depends_on:
      ogok-db:
        condition: service_healthy
  ogok-db:
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_DATABASE}
      TZ: Asia/Seoul
    volumes:
      - ${DB_VOLUMES}
    ports:
      - ${DB_PORT}:3306
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping" ]
      interval: 5s
      retries: 10